### ISSUE TITLE
RosArch package

### ISSUE THREAD

**Issue by jomifred** [jason-lang/jason_ros#21]
place RosArch and other classes in a java package

**Comment by Rezenders** [comment]
http://rosjava.github.io/rosjava_core/0.1.6/best_practices.html#java-package-names

**Comment by Rezenders** [comment]
Named jasonros for simplicity
Done at 860be94

**Comment by jomifred** [comment]
a java class in package jasonros have to be placed in a folder named jasonros.

> On 11 Apr 2019, at 20:23, Gustavo Rezende <notifications@github.com> wrote:
> 
> Named jasonros for simplicity
> Done at 860be94
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)
